package com.newops.regulacao;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class negacao implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Código")
	private java.lang.Integer codigo;
	@org.kie.api.definition.type.Label(value = "Negação")
	private java.lang.String negacao;

	public negacao() {
	}

	public java.lang.Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(java.lang.Integer codigo) {
		this.codigo = codigo;
	}

	public java.lang.String getNegacao() {
		return this.negacao;
	}

	public void setNegacao(java.lang.String negacao) {
		this.negacao = negacao;
	}

	public negacao(java.lang.Integer codigo, java.lang.String negacao) {
		this.codigo = codigo;
		this.negacao = negacao;
	}

}