package com.newops.regulacao;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class solicitante implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Código")
	private java.lang.Integer codigo;
	@org.kie.api.definition.type.Label(value = "Nome")
	private java.lang.String nome;
	@org.kie.api.definition.type.Label(value = "Especialidade")
	private java.lang.String especialidade;

	public solicitante() {
	}

	public java.lang.Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(java.lang.Integer codigo) {
		this.codigo = codigo;
	}

	public java.lang.String getNome() {
		return this.nome;
	}

	public void setNome(java.lang.String nome) {
		this.nome = nome;
	}

	public java.lang.String getEspecialidade() {
		return this.especialidade;
	}

	public void setEspecialidade(java.lang.String especialidade) {
		this.especialidade = especialidade;
	}

	public solicitante(java.lang.Integer codigo, java.lang.String nome,
			java.lang.String especialidade) {
		this.codigo = codigo;
		this.nome = nome;
		this.especialidade = especialidade;
	}

}