package com.newops.regulacao;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class solicitacao implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Nome")
	private java.lang.String nome;
	@org.kie.api.definition.type.Label("Idade")
	private java.lang.Integer idade;

	@org.kie.api.definition.type.Label("Autorizado")
	private java.lang.Boolean autorizado;

	@org.kie.api.definition.type.Label("Id")
	private java.lang.Integer id;

	@org.kie.api.definition.type.Label("Data da Solicitacao")
	private java.util.Date datasolicitacao;

	@org.kie.api.definition.type.Label("Especialidade")
	private java.lang.String especialidade;

	@org.kie.api.definition.type.Label("Justificativa ou Observação")
	private java.lang.String justificativaobs;

	public solicitacao() {
	}

	public java.lang.String getNome() {
		return this.nome;
	}

	public void setNome(java.lang.String nome) {
		this.nome = nome;
	}

	public java.lang.Integer getIdade() {
		return this.idade;
	}

	public void setIdade(java.lang.Integer idade) {
		this.idade = idade;
	}

	public java.lang.Boolean getAutorizado() {
		return this.autorizado;
	}

	public void setAutorizado(java.lang.Boolean autorizado) {
		this.autorizado = autorizado;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.util.Date getDatasolicitacao() {
		return this.datasolicitacao;
	}

	public void setDatasolicitacao(java.util.Date datasolicitacao) {
		this.datasolicitacao = datasolicitacao;
	}

	public java.lang.String getEspecialidade() {
		return this.especialidade;
	}

	public void setEspecialidade(java.lang.String especialidade) {
		this.especialidade = especialidade;
	}

	public java.lang.String getJustificativaobs() {
		return this.justificativaobs;
	}

	public void setJustificativaobs(java.lang.String justificativaobs) {
		this.justificativaobs = justificativaobs;
	}

	public solicitacao(java.lang.String nome, java.lang.Integer idade,
			java.lang.Boolean autorizado, java.lang.Integer id,
			java.util.Date datasolicitacao, java.lang.String especialidade,
			java.lang.String justificativaobs) {
		this.nome = nome;
		this.idade = idade;
		this.autorizado = autorizado;
		this.id = id;
		this.datasolicitacao = datasolicitacao;
		this.especialidade = especialidade;
		this.justificativaobs = justificativaobs;
	}

}